<?php
/**
 * 订单列表导出
 * 用于圆通电子面单批量生成
 * Created by PhpStorm.
 * User: leo
 * Date: 2019/8/26
 * Time: 17:09
 */

namespace App\Admin\Extensions;

use Encore\Admin\Grid\Exporters\ExcelExporter;
use Illuminate\Support\Carbon;
use Maatwebsite\Excel\Facades\Excel;

class OrdersExporter extends ExcelExporter
{
    protected $fileName = '订单列表.xls';

    protected $headingsYw = [
        '进线公司',
        '进线日期',
        '日期',
        '盒数',
        '价格',
        '口味',
        '支付方式',
        '收订',
        '代收',
        '销售员',
        '微信编号',
        '收货地址详情',
        '备注',
        '年龄',
        '快递时间',
        '快递费',
        '快递公司',
        '赠送抵用卷'
    ];

    public function export()
    {
//        parent::export(); // TODO: Change the autogenerated stub

        $rows = [];
        $rows[] = $this->headingsYw;

        $data = $this->getData();

        $payment_method = [
            'WeChatPay' => '微信支付',
            'AliPay'    => '支付宝支付',
            'fubei'     => '付呗'
        ];

        $express_company = [
            'SF'       => '顺丰快递',
            'YTO'      => '圆通快递'
        ];

        if (count($data)) {
            foreach ($data as $v) {
                $info = \DB::table('wechat_to_channels')->where([['datetime', '=', Carbon::parse($v['transaction_datetime'])->toDateString()], ['wechat_id', '=', $v['wechat_id']]])
                    ->leftJoin('channels','wechat_to_channels.channel_id','=','channels.id')
                    ->first();
                $wechat = \DB::table('wechat')->where('id',$v['wechat_id'])->value('code');
                $company = $info ? $info->name : '';
                $user_name = \DB::table('users')->where('id',$v['user_id'])->value('name');
                $row = [];
                // 进线公司
                // 获取当天该微信号的进线渠道
                $row['company']                   = $company;
                $row['datetime']                  = Carbon::parse($v['datetime'])->toDateString();
                $row['transaction_datetime']      = Carbon::parse($v['transaction_datetime'])->toDateString();
                $row['quantity']                  = $v['quantity'];
                $row['total_amount']              = $v['total_amount'];
                $row['taste']                     = $v['taste'];
                $row['payment_method']            = $payment_method[$v['payment_method']];
                $row['prepayments']               = $v['prepayments'];
                $row['tail']                      = $v['total_amount'] - $v['prepayments'];
                $row['seller']                    = $user_name;
                $row['wechat']                    = $wechat;
                $row['addr']                      = $v['address']['province'].$v['address']['city'].$v['address']['district'].$v['address']['address']
                    .' '.$v['fans_name'].' '.$v['phone_number'].' ';
                $row['mark']                      = $v['mark'];
                $row['age']                       = $v['age'];
                $row['express_time']              = '';
                $row['express_price']             = '';
                $row['express_company']           = $express_company[$v['ship_data']['ShipperCode']];
                $row['coupon']                    = '';
                $rows[] = $row;
            }
        }
        //dd($rows);
        // 数据格式化
        $export = new InvoicesExport($rows);

        // 导出
        return Excel::download($export, $this->fileName, \Maatwebsite\Excel\Excel::XLS)->send();
    }
}
