<?php
/**
 * Created by PhpStorm.
 * User: leo
 * Date: 2019/8/26
 * Time: 17:09
 */

namespace App\Admin\Extensions;

use Encore\Admin\Grid\Exporters\ExcelExporter;
use Maatwebsite\Excel\Facades\Excel;

class OrdersExporter extends ExcelExporter
{
    protected $fileName = '订单列表.xls';

    protected $headingsYb = [
        '物流订单号(选填，若不填则系统自动生成；若填则不允许重复)',
        '商品名称(选填)',
        '数量（选填）',
        '收件人姓名（必填）',
        '收件人省（必填）',
        '收件人市（必填）',
        '收件人区（必填）',
        '收件人地址（必填，不包含省市区）',
        '收件人手机号（必填）',
        '发件人姓名（必填）',
        '发件人电话（选填）',
        '发件人省（必填）',
        '发件人市（必填）',
        '发件人区（必填）,',
        '发件地址（必填，不包含省市区）',
        '发件人邮编（选填）',
        '代收货款（选填）',
        '备注（选填）',
        '收件人邮编（选填）',
        '收件人固话（选填）',
        '保价金额（选填）'
    ];
    protected $headingsYw = [
        '物流订单号(选填，若不填则系统自动生成；若填则不允许重复)',
        '商品名称(选填)',
        '数量（选填）',
        '收件人姓名（必填）',
        '收件人地址（必填，必须包含省市区）',
        '收件人手机号（必填）',
        '发件人姓名（必填）',
        '发件人电话（选填）',
        '发件人地址（必填，必须包含省市区）',
        '发件人邮编（选填）',
        '代收货款（选填）',
        '备注（选填）',
        '收件人邮编（选填）',
        '收件人固话（选填）',
        '保价金额（选填）'
    ];


//    protected $columns = [
//        'no' => '物流订单号(选填，若不填则系统自动生成；若填则不允许重复)',
//        'goods_name' => '商品名称(选填)',
//        'goods_number' => '数量（选填）',
//        'fans_name' => '收件人姓名（必填）',
//        'province' => '收件人省（必填）',
//        'city' => '收件人市（必填）',
//        'district' => '收件人区（必填）',
//        'address' => '收件人地址（必填，不包含省市区）',
//        'phone_number' => '收件人手机号（必填）',
//        'send_name' => '发件人姓名（必填）',
//        'send_phone' => '发件人电话（选填）',
//        'send_province' => '发件人省（必填）',
//        'send_city' => '发件人市（必填）',
//        'send_district' => '发件人区（必填）,',
//        'send_address' => '发件地址（必填，不包含省市区）',
//        'send_postcode' => '发件人邮编（选填）',
//        'collection' => '代收货款（选填）',
//        'remark' => '备注（选填）',
//        'postcode' => '收件人邮编（选填）',
//        'tel' => '收件人固话（选填）',
//        'insurance_price' => '保价金额（选填）'
//    ];


    public function export()
    {
//        parent::export(); // TODO: Change the autogenerated stub

        $rows = [];
        $rows[] = $this->headingsYw;

        $data = $this->getData();

        if (count($data)) {
            foreach ($data as $v) {
                $row = [];
                $row['no'] = $v['no'];
                $row['goods_name'] = '';
                $row['goods_number'] = '';
                $row['fans_name'] = $v['fans_name'];
//                $row['province'] = $v['address']['province'];
//                $row['city'] = $v['address']['city'];
//                $row['district'] = $v['address']['district'];
                $row['address'] = $v['address']['province'].$v['address']['city'].$v['address']['district'].$v['address']['address'];
                $row['phone_number'] = $v['phone_number'];
                $row['send_name'] = '杨武东';
                $row['send_phone'] = '13677344771';
//                $row['send_province'] = '湖南省';
//                $row['send_city'] = '长沙市';
//                $row['send_district'] = '岳麓区';
//                $row['send_address'] = '发件地址（必填，不包含省市区）';
                $row['send_address'] = '湖南省长沙市岳麓区新长沙中心B3栋206';
                $row['send_postcode'] = '';
                $row['collection'] = $v['total_amount'] - $v['prepayments'];
                $row['remark'] = $v['remark'];
                $row['postcode'] = '';
                $row['tel'] = '';
                $row['insurance_price'] = '';
                $rows[] = $row;
            }
        }
        //dd($rows);
        // 数据格式化
        $export = new InvoicesExport($rows);

        // 导出
        return Excel::download($export, $this->fileName, \Maatwebsite\Excel\Excel::XLS)->send();
    }
}
